title: Controlz
description: The flexible, easy to use, all in one library for your Android project.
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  - jekyll-readme-index