# Thanks to https://github.com/coil-kt/coil/blob/master/.github/workflows/ci.yml

name: Android CI

on:
    push:
        branches:
            - master
    pull_request:
    
jobs:
    ci:
        name: Build + Test
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout current repository in ubuntu's file system
              uses: actions/checkout@v1
              with:
                submodules: recursive
            
            - name: Setup JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

            # Ensure .gradle/caches is empty before writing to it.
            # This helps us stay within Github's cache size limits.
            - name: Clean Cache
              run: rm -rf ~/.gradle/caches

            # Restore the cache.
            # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
            - uses: actions/cache@v1
              with:
                path: ~/.gradle/caches
                key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

            - name: Build project
                run: .github/scripts/gradlew_recursive.sh assembleDebug
            - name: Zip artifacts
                run: zip -r assemble.zip . -i '**/build/*.apk' '**/build/*.aab' '**/build/*.aar' '**/build/*.so'
            - name: Upload artifacts
                uses: actions/upload-artifact@v1
                with:
                    name: assemble
                    path: assemble.zip
          
            #- name: Build
            #  run: ./gradlew clean build --warning-mode=all --stacktrace
              
            #- name: Print contents in current directory
            #  run: ls -la

            #- name: Detekt
            #  run: ./gradlew detekts